---
.travis.yml:
  includes:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.2.6
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.3.3
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=rubocop
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=build
Gemfile:
  required:
    ':test':
      - gem: puppetlabs_spec_helper
        version: '~> 2.1.1'
      - gem: rspec-puppet
        version: '~> 2.5'
      - gem: rspec-puppet-facts
      - gem: rspec-puppet-utils
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: metadata-json-lint
      - gem: puppet-blacksmith
      - gem: voxpupuli-release
        git: https://github.com/voxpupuli/voxpupuli-release-gem.git
      - gem: puppet-strings
        version: '~> 1.0.0'
      - gem: redcarpet
      - gem: rubocop
        version: '~> 0.47.0'
        ruby-operator: '>='
        ruby-version: '2.3.0'
      - gem: rubocop-rspec
        version: '~> 1.10.0'
        ruby-operator: '>='
        ruby-version: '2.3.0'
      - gem: mocha
        version: '>= 1.2.1'
      - gem: coveralls
      - gem: simplecov-console
      - gem: github_changelog_generator
        version: '~> 1.13.0'
        ruby-operator: '<'
        ruby-version: '2.2.2'
      - gem: rack
        version: '~> 1.0'
        ruby-operator: '<'
        ruby-version: '2.2.2'
      - gem: github_changelog_generator
        ruby-operator: '>='
        ruby-version: '2.2.2'
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_140chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
  default_enabled_rake_targets:
  - 'metadata_lint'
  - 'release_checks'
.env.sh: {}
Jenkinsfile: {}
# vim: syntax=yaml
