---
.travis.yml:
  docker_sets:
  docker_defaults:
    # values will replace @@SET@@ with the docker_sets' value
  - rvm: 2.5.3
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=@@SET@@ BEAKER_HYPERVISOR=docker CHECK=beaker
    bundler_args: --without development release
  - rvm: 2.5.3
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=@@SET@@ BEAKER_HYPERVISOR=docker CHECK=beaker
    bundler_args: --without development release
  includes:
  - rvm: 2.4.4
    env: PUPPET_VERSION="~> 5.0" CHECK=test
    bundler_args: --without system_tests development release
  - rvm: 2.5.3
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
    bundler_args: --without system_tests development release
  - rvm: 2.5.3
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
    bundler_args: --without system_tests development release
  - rvm: 2.4.4
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
    bundler_args: --without system_tests development release
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
    - "chat.freenode.org#voxpupuli-notifications"
  user: puppet
Gemfile:
  required:
    ':test':
      - gem: puppetlabs_spec_helper
        version: '>= 2.14.0'
      - gem: rspec-puppet-facts
        version: '>= 1.9.5'
      - gem: rspec-puppet-utils
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-topscope-variable-check
      - gem: puppet-lint-legacy_facts-check
      - gem: puppet-lint-anchor-check
      - gem: metadata-json-lint
      - gem: redcarpet
      - gem: rubocop
        version: '~> 0.49.1'
      - gem: rubocop-rspec
        version: '~> 1.15.0'
      - gem: mocha
        version: '~> 1.4.0'
      - gem: coveralls
      - gem: simplecov-console
      - gem: parallel_tests
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
      - gem: overcommit
        version: '>= 0.39.1'
    ':system_tests':
      - gem: winrm
      - gem: beaker-rspec
        version: '>= 6'
      - gem: serverspec
      - gem: beaker-hostgenerator
        version: '>= 1.1.22'
      - gem: beaker-docker
      - gem: beaker-puppet
      - gem: beaker-puppet_install_helper
      - gem: beaker-module_install_helper
        require: false
      - gem: rbnacl
        version: '>= 4'
      - gem: rbnacl-libsodium
      - gem: bcrypt_pbkdf
    ':release':
      - gem: github_changelog_generator
        git: https://github.com/voxpupuli/github-changelog-generator
        branch: voxpupuli_essential_fixes
      - gem: puppet-blacksmith
      - gem: voxpupuli-release
      - gem: puppet-strings
        version: '>= 2.2'
.env.sh: {}
Jenkinsfile: {}
Rakefile:
  config.user: voxpupuli
  exclude_paths: []
  puppet_lint_checks: []
  puppet_strings_patterns: []
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_140chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
  default_enabled_rake_targets:
  - 'metadata_lint'
  - 'release_checks'
spec/default_facts.yml:
  delete: true
spec/classes/coverage_spec.rb:
  delete: true
spec/acceptance/nodesets/centos-511-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-6-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64-pe.yml:
  delete: true
spec/acceptance/nodesets/centos-7-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-72-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-78-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-82-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-20-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-24-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-25-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-26-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-27-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1604-x64.yml:
  delete: true
spec/spec_helper.rb:
  mock_with: ':rspec'
  facterdb_facts_version: '3.9.0'
...
# vim: syntax=yaml
